// site-admin/src/views/component/ComponentAction.vue
<template>
  <main class="px-4 pb-[60px] pt-0">
    <div class="space-y-8">
      <div>
        <div class="flex items-center justify-between">
          <h3 class="text-lg font-medium leading-6 text-gray-900">Component</h3>
          <button v-if="id" @click="close()"
            class="rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:ring-offset-2 flex items-center justify-between">
            Close
            <ChevronUpIcon class="w-6 h-6 ml-2" />
          </button>
        </div>
        <p class="mt-1 text-sm text-gray-500">
          This information will be displayed publicly so be careful what you
          share.
        </p>
      </div>
      <div>
        <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
          <div class="sm:col-span-3">
            <div
              class="relative rounded-md border border-gray-300 px-3 py-3 focus-within:border-indigo-600 focus-within:ring-1 focus-within:ring-indigo-600">
              <label for="title"
                class="absolute -top-2 left-2 -mt-px inline-block bg-white px-1 text-xs font-medium text-gray-900">Title</label>
              <input v-model="title" type="text" name="title" id="title" autocomplete="off"
                class="block w-full border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm disabled:bg-gray-20 disabled:text-gray-400 disabled:cursor-not-allowed"
                placeholder="Enter title" />
              <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center pr-3">
                <ExclamationCircleIcon v-if="title.length < 3" class="h-5 w-5 text-red-500" aria-hidden="true" />
                <CheckCircleIcon v-else class="h-5 w-5 text-green-500" aria-hidden="true" />
              </div>
            </div>
          </div>
          <div class="sm:col-span-2">
            <Listbox as="div" class="relative" v-model="selectedCategory">
              <ListboxLabel
                class="absolute -top-2 left-2 -mt-px inline-block bg-white px-1 text-xs font-medium text-gray-900 z-10">
                Category</ListboxLabel>
              <div class="relative">
                <ListboxButton
                  class="relative w-full cursor-default rounded-md border border-gray-300 bg-white py-3 pl-3 pr-10 text-left focus:outline-none sm:text-sm">
                  <span class="flex items-center">
                    <span class="block truncate">{{
                      selectedCategory.title
                      }}</span>
                  </span>
                  <span class="pointer-events-none absolute inset-y-0 right-0 ml-3 flex items-center pr-2">
                    <ChevronUpDownIcon class="h-5 w-5 text-gray-400" aria-hidden="true" />
                  </span>
                </ListboxButton>

                <transition leave-active-class="transition ease-in duration-100" leave-from-class="opacity-100"
                  leave-to-class="opacity-0">
                  <ListboxOptions
                    class="absolute z-40 mt-1 max-h-56 w-full overflow-auto scrollbar-thin scrollbar-thumb-gray-100 scrollbar-track-gray-300 rounded-md bg-white py-1 text-base shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none sm:text-sm">
                    <ListboxOption as="template"
                      v-for="category in componentCategories.sort((a, b) => a.priority - b.priority)" :key="category.id"
                      :value="category" v-slot="{ active, selected }">
                      <li :class="[
                        active ? 'text-white bg-indigo-600' : 'text-gray-900',
                        'relative cursor-default select-none py-2 pl-3 pr-9',
                      ]">
                        <div class="flex items-center">
                          <span :class="[
                            selected ? 'font-semibold' : 'font-normal',
                            'block truncate',
                          ]">{{ category.title }}</span>
                        </div>

                        <span v-if="selected" :class="[
                          active ? 'text-white' : 'text-indigo-600',
                          'absolute inset-y-0 right-0 flex items-center pr-4',
                        ]">
                          <CheckIcon class="h-5 w-5" aria-hidden="true" />
                        </span>
                      </li>
                    </ListboxOption>
                  </ListboxOptions>
                </transition>
              </div>
            </Listbox>
          </div>
          <div class="sm:col-span-1">
            <div
              class="relative rounded-md border border-gray-300 px-3 py-3 focus-within:border-indigo-600 focus-within:ring-1 focus-within:ring-indigo-600">
              <label for="priority"
                class="absolute -top-2 left-2 -mt-px inline-block bg-white px-1 text-xs font-medium text-gray-900">Priority</label>
              <input v-model.number="priority" type="number" name="priority" id="priority" autocomplete="off"
                class="block w-full border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm disabled:bg-gray-20 disabled:text-gray-400 disabled:cursor-not-allowed"
                placeholder="Enter priority" />
              <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center pr-3">
                <ExclamationCircleIcon v-if="priority == 0" class="h-5 w-5 text-red-500" aria-hidden="true" />
                <CheckCircleIcon v-else class="h-5 w-5 text-green-500" aria-hidden="true" />
              </div>
            </div>
          </div>
          <div class="sm:col-span-6">
            <div
              class="relative rounded-md border border-gray-300 px-3 py-3 focus-within:border-indigo-600 focus-within:ring-1 focus-within:ring-indigo-600">
              <label for="componentData"
                class="absolute -top-2 left-2 -mt-px inline-block bg-white px-1 text-xs font-medium text-gray-900">Component
                Data</label>
              <textarea v-model="componentData" type="text" name="componentData" id="componentData" autocomplete="off"
                class="block w-full min-h-[400px] border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm disabled:bg-gray-20 disabled:text-gray-400 disabled:cursor-not-allowed"
                placeholder="Enter componentData" />
              <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center pr-3">
                <ExclamationCircleIcon v-if="componentData.length < 3" class="h-5 w-5 text-red-500"
                  aria-hidden="true" />
                <CheckCircleIcon v-else class="h-5 w-5 text-green-500" aria-hidden="true" />
              </div>
            </div>
          </div>
          <div class="sm:col-span-6">
            <div
              class="relative rounded-md border border-gray-300 px-3 py-3 focus-within:border-indigo-600 focus-within:ring-1 focus-within:ring-indigo-600">
              <label for="description"
                class="absolute -top-2 left-2 -mt-px inline-block bg-white px-1 text-xs font-medium text-gray-900">Image</label>
              <file-pond class="bg-white pt-4 px-2" :files="files" @onAdded="onAdded" />
            </div>
          </div>
        </div>
        <div class="pt-6">
          <h3 class="text-lg font-medium leading-6 text-gray-900">Status</h3>
          <p class="mt-1 text-sm text-gray-500">
            The details used to determine your category behaviour around the
            web.
          </p>
        </div>
        <div class="mt-2">
          <fieldset>
            <div class="mt-4 space-y-4">
              <div class="relative flex items-start">
                <div class="flex h-5 items-center">
                  <input v-model="isActive" id="isActive" name="isActive" type="checkbox"
                    class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500" />
                </div>
                <div class="ml-3 text-sm">
                  <label for="isActive" class="font-medium text-gray-700">Active</label>
                  <p class="text-gray-500">
                    User can view and filter products.
                  </p>
                </div>
              </div>
            </div>
          </fieldset>
        </div>
        <div class="pt-5">
          <div class="flex justify-end">
            <router-link @click="close()" :to="`/component`" type="button"
              class="rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:ring-offset-2">Cancel</router-link>
            <button v-if="
                actionType == 'ComponentUpdate'" @click="update()" type="submit"
              class="ml-3 inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:ring-offset-2">
              Update</button><button v-else @click="create()" type="submit"
              class="ml-3 inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:ring-offset-2">
              Save
            </button>
            <button v-if="
                actionType == 'ComponentUpdate'
              " @click="
                toggleAlert(
                  'Delete Component!',
                  'Are you sure you want to delete your component? All of your data will be permanently removed from our servers forever. This action cannot be undone.',
                  'error'
                )
              " type="submit"
              class="ml-3 inline-flex justify-center rounded-md border border-transparent bg-red-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2">
              Delete
            </button>
          </div>
        </div>
      </div>
    </div>
    <Alert v-if="showAlert" :message="alertMessage" @confirmed="remove" @canceled="onCanceled"></Alert>
  </main>
</template>
<script setup>
import {
  SELF_SITE_COMPONENT_CREATE,
  SELF_SITE_COMPONENT_UPDATE,
  SELF_SITE_COMPONENT_DELETE,
  SITE_COMPONENT,
} from "@/gql/site";
import { useQuery, useMutation } from "@vue/apollo-composable";
import {
  ExclamationCircleIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronUpDownIcon, ChevronUpIcon
} from "@heroicons/vue/24/outline";
import {
  Listbox,
  ListboxButton,
  ListboxLabel,
  ListboxOption,
  ListboxOptions,
} from "@headlessui/vue";
import { computed, ref, onMounted, defineAsyncComponent } from "vue";
import { useRouter } from "vue-router";
import { storeToRefs } from "pinia";
import { useMeStore } from "@/stores/me";
import { useComponentStore } from "@/stores/component";
import { useNotificationsStore } from "@/stores/notifications";
const { addNotification } = useNotificationsStore();
const FilePond = defineAsyncComponent(() =>
  import("@/components/FilePond.vue")
);
const Alert = defineAsyncComponent(() =>
  import("@/components/Alert.vue")
);
const router = useRouter();
const { componentId, components, componentCategories } = storeToRefs(useComponentStore());
const { getComponents, getComponentCategories } = useComponentStore();
const { me } = storeToRefs(useMeStore());

if (componentCategories.value.length == 0) {
  getComponentCategories();
}
const selectedCategory = ref({
  title: "Category",
  id: null,
});
const categoryId = ref(1);
const component = ref("");
const componentData = ref({});
const description = ref("");
const image = ref(null);
const isActive = ref(true);
const priority = ref(0);
const settings = ref({});
const slug = ref("");
const title = ref("");

const files = ref([]);
const alertMessage = ref({});
const showAlert = ref(false);

const props = defineProps({
  id: {
    type: Number,
    required: false,
  },
});
const actionType = computed(() =>
  props.id ? "ComponentUpdate" : router.currentRoute.value.name
);
if (actionType.value == "ComponentUpdate" && componentId.value) {
  const { onResult, loading, error } = useQuery(SITE_COMPONENT, {
    id: props.id ? props.id : componentId.value,
  });
  onResult((queryResult) => {
    let item = queryResult.data.siteComponent;
    categoryId.value = item.categoryId;
    component.value = item.component;
    componentData.value = JSON.stringify(item.componentData);
    description.value = item.description;
    image.value = null;
    isActive.value = item.isActive;
    priority.value = item.priority;
    slug.value = item.slug;
    title.value = item.title;
    files.value = [item.image];
    // 
    let found = componentCategories.value.find(c => c.id == item.categoryId);
    if (found) {
      selectedCategory.value = found;
    }
  });
}

const onAdded = (file) => {
  if (
    files.value.length > 0 &&
    files.value[0].split("/")[files.value[0].split("/").length - 1] == file.name
  ) {
    image.value = null;
  } else {
    const maxSizeInBytes = 3 * 1024 * 1024; // Specify the maximum file size in bytes (e.g., 10MB)
    if (file && file.size <= maxSizeInBytes && files.value[0] != file.name) {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onloadend = () => {
        image.value = file;
      };
    } else {
      addNotification(
        {
          title: "Product info",
          subTitle: "File size exceeds the maximum (3 MB) allowed limit.",
        },
        "error"
      );
    }
  }
};

const create = async () => {
  const { mutate, loading, error } = useMutation(SELF_SITE_COMPONENT_CREATE, {
    variables: {
      userId: me.value.id,
      categoryId: selectedCategory.value.id ? selectedCategory.value.id : categoryId.value,
      component: component.value,
      componentData: JSON.parse(componentData.value),
      description: description.value,
      image: image.value,
      isActive: isActive.value,
      priority: priority.value,
      settings: settings.value,
      slug: slug.value,
      title: title.value,
    },
  });
  try {
    const response = await mutate();
    if (response.data.selfSiteComponentCreate) {
      addNotification(
        { title: "Component info", subTitle: "Successfully updated new data." },
        "success"
      );
      componentId.value = response.data.selfSiteComponentCreate.id;
      router.push(`/component/update/`);
    }
  } catch (error) {
    addNotification({ title: "Component info", subTitle: error.message }, "error");
  }
};
const update = async () => {
  const { mutate, loading, error } = useMutation(SELF_SITE_COMPONENT_UPDATE, {
    variables: {
      userId: me.value.id,
      componentId: componentId.value,
      categoryId: selectedCategory.value.id ? selectedCategory.value.id : categoryId.value,
      component: component.value,
      componentData: JSON.parse(componentData.value),
      description: description.value,
      image: image.value,
      isActive: isActive.value,
      priority: priority.value,
      settings: settings.value,
      slug: slug.value,
      title: title.value,
    },
  });
  try {
    const response = await mutate();
    if (response.data.selfSiteComponentUpdate) {
      addNotification(
        { title: "Component info", subTitle: "Successfully updated new data." },
        "success"
      );
    }
  } catch (error) {
    addNotification({ title: "Component info", subTitle: error.message }, "error");
  }
};
const remove = async () => {
  const { mutate, loading, error } = useMutation(SELF_SITE_COMPONENT_DELETE, {
    variables: {
      userId: me.value.id,
      componentId: componentId.value,
    },
  });
  try {
    const response = await mutate();
    if (response.data.selfSiteComponentDelete) {
      addNotification(
        { title: "Component info", subTitle: "Successfully updated new data." },
        "success"
      );
      router.push(`/component/`);
    }
  } catch (error) {
    addNotification({ title: "Component info", subTitle: error.message }, "error");
  }
};
const toggleAlert = (title, message, type) => {
  alertMessage.value = {
    title: title,
    message: message,
    type: type,
  };
  showAlert.value = true;
};

const onCanceled = () => {
  showAlert.value = false;
};
onMounted(() => {
  if (props.id) {
    componentId.value = props.id;
  }
});
const emit = defineEmits(["close"]);
const close = () => {
  emit("close");
};
</script>

// src/siteAdmin/pages/ComponentAction.tsx
import { Fragment, useEffect, useMemo, useState } from "react";
import { useMutation, useQuery } from "@apollo/client";
import { Listbox, Transition } from "@headlessui/react";
import {
  CheckCircleIcon,
  CheckIcon,
  ChevronUpDownIcon,
  ExclamationCircleIcon
} from "@heroicons/react/24/outline";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import {
  SITE_COMPONENT,
  SITE_COMPONENT_CATEGORIES
} from "@/graphql/queries/siteComponents";
import {
  SELF_SITE_COMPONENT_CREATE,
  SELF_SITE_COMPONENT_DELETE,
  SELF_SITE_COMPONENT_UPDATE
} from "@/graphql/mutations/siteComponents";
import { useAuthStore } from "@/store/useAuthStore";
import { useToastStore } from "@/siteAdmin/store/useToastStore";

type Category = {
  id: number;
  title: string;
  priority?: number | null;
};

function safeJsonStringify(value: unknown) {
  try {
    return JSON.stringify(value ?? {}, null, 2);
  } catch {
    return "{}";
  }
}

function safeJsonParse(text: string): unknown | null {
  try {
    return JSON.parse(text);
  } catch {
    return null;
  }
}

function slugify(value: string) {
  return value
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export default function ComponentAction() {
  const navigate = useNavigate();
  const [params] = useSearchParams();
  const user = useAuthStore((s) => s.user);
  const addToast = useToastStore((s) => s.addToast);

  const idParam = params.get("id");
  const componentId = idParam ? Number(idParam) : null;
  const isUpdate = !!(componentId && Number.isFinite(componentId));

  const categoriesQuery = useQuery(SITE_COMPONENT_CATEGORIES, {
    variables: { first: 200, after: null },
    fetchPolicy: "network-only"
  });

  const categories: Category[] = useMemo(() => {
    const edges = categoriesQuery.data?.siteComponentCategories?.edges ?? [];
    return edges.map((e: any) => e.node).filter(Boolean);
  }, [categoriesQuery.data]);

  const sortedCategories = useMemo(() => {
    return [...categories].sort((a, b) => (a.priority ?? 0) - (b.priority ?? 0));
  }, [categories]);

  const componentQuery = useQuery(SITE_COMPONENT, {
    variables: { id: componentId ?? 0 },
    fetchPolicy: "network-only",
    skip: !isUpdate
  });

  const component = componentQuery.data?.siteComponent ?? null;

  const [title, setTitle] = useState("");
  const [selectedCategory, setSelectedCategory] = useState<Category | null>(null);
  const [priority, setPriority] = useState<number>(0);
  const [slug, setSlug] = useState("");
  const [description, setDescription] = useState("");
  const [componentName, setComponentName] = useState("");
  const [componentDataText, setComponentDataText] = useState("{}");
  const [settingsText, setSettingsText] = useState("{}");
  const [isActive, setIsActive] = useState(true);
  const [imageFile, setImageFile] = useState<File | null>(null);

  useEffect(() => {
    if (!sortedCategories.length || selectedCategory) return;
    setSelectedCategory(sortedCategories[0] ?? null);
  }, [selectedCategory, sortedCategories]);

  useEffect(() => {
    if (!component) return;
    setTitle(String(component.title ?? ""));
    setPriority(Number(component.priority ?? 0));
    setSlug(String(component.slug ?? ""));
    setDescription(String(component.description ?? ""));
    setComponentName(String(component.component ?? ""));
    setComponentDataText(safeJsonStringify(component.componentData));
    setSettingsText(safeJsonStringify(component.settings));
    setIsActive(!!component.isActive);
    const cat = sortedCategories.find((c) => c.id === component.categoryId) ?? null;
    setSelectedCategory(cat);
    setImageFile(null);
  }, [component?.id, sortedCategories]);

  const [createComponent, createState] = useMutation(SELF_SITE_COMPONENT_CREATE, {
    onCompleted: () => {
      addToast({ kind: "success", title: "Component", subTitle: "Created." });
      navigate("/component/", { replace: true });
    },
    onError: (err) => addToast({ kind: "error", title: "Component", subTitle: err.message })
  });

  const [updateComponent, updateState] = useMutation(SELF_SITE_COMPONENT_UPDATE, {
    onCompleted: () => {
      addToast({ kind: "success", title: "Component", subTitle: "Updated." });
      navigate("/component/", { replace: true });
    },
    onError: (err) => addToast({ kind: "error", title: "Component", subTitle: err.message })
  });

  const [deleteComponent, deleteState] = useMutation(SELF_SITE_COMPONENT_DELETE, {
    onCompleted: () => {
      addToast({ kind: "success", title: "Component", subTitle: "Deleted." });
      navigate("/component/", { replace: true });
    },
    onError: (err) => addToast({ kind: "error", title: "Component", subTitle: err.message })
  });

  const saving = createState.loading || updateState.loading;

  const handleSave = async () => {
    if (!user?.id) return;
    const categoryId = selectedCategory?.id ?? null;
    if (!categoryId) {
      addToast({ kind: "error", title: "Validation", subTitle: "Select category." });
      return;
    }
    const parsedComponentData = safeJsonParse(componentDataText);
    const parsedSettings = safeJsonParse(settingsText);
    if (parsedComponentData == null) {
      addToast({ kind: "error", title: "Validation", subTitle: "Invalid componentData JSON." });
      return;
    }
    if (parsedSettings == null) {
      addToast({ kind: "error", title: "Validation", subTitle: "Invalid settings JSON." });
      return;
    }
    const effectiveSlug = slug.trim() || slugify(title);
    if (!effectiveSlug) {
      addToast({ kind: "error", title: "Validation", subTitle: "Slug is required." });
      return;
    }

    if (isUpdate) {
      await updateComponent({
        variables: {
          userId: user.id,
          componentId,
          categoryId,
          title,
          priority,
          slug: effectiveSlug,
          description,
          component: componentName,
          componentData: parsedComponentData,
          settings: parsedSettings,
          isActive,
          image: imageFile ?? null
        }
      });
      return;
    }

    if (!imageFile) {
      addToast({ kind: "error", title: "Validation", subTitle: "Image is required for create." });
      return;
    }

    await createComponent({
      variables: {
        userId: user.id,
        categoryId,
        title,
        priority,
        slug: effectiveSlug,
        description,
        component: componentName,
        componentData: parsedComponentData,
        settings: parsedSettings,
        isActive,
        image: imageFile
      }
    });
  };

  const handleDelete = async () => {
    if (!user?.id || !isUpdate) return;
    const ok = window.confirm("Delete Component?");
    if (!ok) return;
    await deleteComponent({ variables: { userId: user.id, componentId } });
  };

  return (
    <main className="px-4 pb-16 pt-0">
      <div className="space-y-8">
        <div>
          <div className="flex items-center justify-between">
            <h3 className="text-lg font-medium leading-6 text-slate-900">
              Component
            </h3>
            {isUpdate ? (
              <button
                type="button"
                onClick={() => navigate("/component/")}
                className="rounded-md border border-slate-300 bg-white py-2 px-4 text-sm font-medium text-slate-700 shadow-sm hover:bg-slate-50"
              >
                Close
              </button>
            ) : null}
          </div>
          <p className="mt-1 text-sm text-slate-500">
            This information will be displayed publicly so be careful what you share.
          </p>
        </div>

        <div className="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
          <div className="sm:col-span-3">
            <div className="relative rounded-md border border-slate-300 bg-white px-3 py-3 focus-within:border-indigo-600 focus-within:ring-1 focus-within:ring-indigo-600">
              <label className="absolute -top-2 left-2 bg-white px-1 text-xs font-medium text-slate-900">
                Title
              </label>
              <input
                value={title}
                onChange={(e) => {
                  setTitle(e.target.value);
                  if (!slug.trim()) setSlug(slugify(e.target.value));
                }}
                className="block w-full border-0 p-0 text-slate-900 placeholder-slate-400 focus:ring-0 text-sm"
                placeholder="Enter title"
              />
              <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center pr-3">
                {title.trim().length < 3 ? (
                  <ExclamationCircleIcon className="h-5 w-5 text-rose-500" />
                ) : (
                  <CheckCircleIcon className="h-5 w-5 text-emerald-500" />
                )}
              </div>
            </div>
          </div>

          <div className="sm:col-span-2">
            <Listbox value={selectedCategory} onChange={setSelectedCategory}>
              <div className="relative">
                <Listbox.Label className="absolute -top-2 left-2 bg-white px-1 text-xs font-medium text-slate-900 z-10">
                  Category
                </Listbox.Label>
                <Listbox.Button className="relative w-full cursor-default rounded-md border border-slate-300 bg-white py-3 pl-3 pr-10 text-left text-sm">
                  <span className="block truncate">
                    {selectedCategory?.title ?? "Category"}
                  </span>
                  <span className="pointer-events-none absolute inset-y-0 right-0 ml-3 flex items-center pr-2">
                    <ChevronUpDownIcon className="h-5 w-5 text-slate-400" />
                  </span>
                </Listbox.Button>

                <Transition
                  as={Fragment}
                  leave="transition ease-in duration-100"
                  leaveFrom="opacity-100"
                  leaveTo="opacity-0"
                >
                  <Listbox.Options className="absolute z-40 mt-1 max-h-56 w-full overflow-auto rounded-md bg-white py-1 text-sm shadow-lg ring-1 ring-black/5 focus:outline-none">
                    {sortedCategories.map((category) => (
                      <Listbox.Option
                        key={category.id}
                        value={category}
                        className={({ active }) =>
                          [
                            "relative cursor-default select-none py-2 pl-3 pr-9",
                            active ? "bg-indigo-600 text-white" : "text-slate-900"
                          ].join(" ")
                        }
                      >
                        {({ selected, active }) => (
                          <>
                            <span
                              className={[
                                "block truncate",
                                selected ? "font-semibold" : "font-normal"
                              ].join(" ")}
                            >
                              {category.title}
                            </span>
                            {selected ? (
                              <span
                                className={[
                                  "absolute inset-y-0 right-0 flex items-center pr-4",
                                  active ? "text-white" : "text-indigo-600"
                                ].join(" ")}
                              >
                                <CheckIcon className="h-5 w-5" />
                              </span>
                            ) : null}
                          </>
                        )}
                      </Listbox.Option>
                    ))}
                  </Listbox.Options>
                </Transition>
              </div>
            </Listbox>
          </div>

          <div className="sm:col-span-1">
            <div className="relative rounded-md border border-slate-300 bg-white px-3 py-3 focus-within:border-indigo-600 focus-within:ring-1 focus-within:ring-indigo-600">
              <label className="absolute -top-2 left-2 bg-white px-1 text-xs font-medium text-slate-900">
                Priority
              </label>
              <input
                value={priority}
                onChange={(e) => setPriority(Number(e.target.value))}
                type="number"
                className="block w-full border-0 p-0 text-slate-900 placeholder-slate-400 focus:ring-0 text-sm"
                placeholder="0"
              />
              <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center pr-3">
                {priority === 0 ? (
                  <ExclamationCircleIcon className="h-5 w-5 text-rose-500" />
                ) : (
                  <CheckCircleIcon className="h-5 w-5 text-emerald-500" />
                )}
              </div>
            </div>
          </div>

          <div className="sm:col-span-6">
            <div className="relative rounded-md border border-slate-300 bg-white px-3 py-3 focus-within:border-indigo-600 focus-within:ring-1 focus-within:ring-indigo-600">
              <label className="absolute -top-2 left-2 bg-white px-1 text-xs font-medium text-slate-900">
                Slug
              </label>
              <input
                value={slug}
                onChange={(e) => setSlug(e.target.value)}
                className="block w-full border-0 p-0 text-slate-900 placeholder-slate-400 focus:ring-0 text-sm"
                placeholder="hero-1"
              />
            </div>
          </div>

          <div className="sm:col-span-6">
            <div className="relative rounded-md border border-slate-300 bg-white px-3 py-3 focus-within:border-indigo-600 focus-within:ring-1 focus-within:ring-indigo-600">
              <label className="absolute -top-2 left-2 bg-white px-1 text-xs font-medium text-slate-900">
                Component
              </label>
              <input
                value={componentName}
                onChange={(e) => setComponentName(e.target.value)}
                className="block w-full border-0 p-0 text-slate-900 placeholder-slate-400 focus:ring-0 text-sm"
                placeholder="Hero"
              />
            </div>
          </div>

          <div className="sm:col-span-6">
            <div className="relative rounded-md border border-slate-300 bg-white px-3 py-3">
              <label className="absolute -top-2 left-2 bg-white px-1 text-xs font-medium text-slate-900">
                Component Data (JSON)
              </label>
              <textarea
                value={componentDataText}
                onChange={(e) => setComponentDataText(e.target.value)}
                className="mt-4 w-full min-h-40 rounded-md border p-3 font-mono text-xs"
              />
            </div>
          </div>

          <div className="sm:col-span-6">
            <div className="relative rounded-md border border-slate-300 bg-white px-3 py-3">
              <label className="absolute -top-2 left-2 bg-white px-1 text-xs font-medium text-slate-900">
                Settings (JSON)
              </label>
              <textarea
                value={settingsText}
                onChange={(e) => setSettingsText(e.target.value)}
                className="mt-4 w-full min-h-24 rounded-md border p-3 font-mono text-xs"
              />
            </div>
          </div>

          <div className="sm:col-span-6">
            <div className="relative rounded-md border border-slate-300 bg-white px-3 py-3">
              <label className="absolute -top-2 left-2 bg-white px-1 text-xs font-medium text-slate-900">
                Description
              </label>
              <textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                className="mt-4 w-full min-h-24 rounded-md border px-3 py-2 text-sm"
              />
            </div>
          </div>

          <div className="sm:col-span-6">
            <div className="relative rounded-md border border-slate-300 bg-white px-3 py-3">
              <label className="absolute -top-2 left-2 bg-white px-1 text-xs font-medium text-slate-900">
                Image
              </label>
              <input
                type="file"
                accept="image/*"
                className="mt-4 text-sm"
                onChange={(e) => setImageFile(e.target.files?.[0] ?? null)}
              />
              {imageFile ? (
                <div className="mt-2 text-xs text-slate-500">
                  Selected: {imageFile.name}
                </div>
              ) : null}
            </div>
          </div>
        </div>

        <div className="pt-6">
          <h3 className="text-lg font-medium leading-6 text-slate-900">
            Status
          </h3>
          <p className="mt-1 text-sm text-slate-500">
            The details used to determine your component behaviour around the web.
          </p>
        </div>

        <div className="mt-2">
          <label className="inline-flex items-start gap-3">
            <input
              checked={isActive}
              onChange={(e) => setIsActive(e.target.checked)}
              type="checkbox"
              className="mt-1 h-4 w-4 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
            />
            <span>
              <span className="block text-sm font-medium text-slate-700">
                Active
              </span>
              <span className="block text-sm text-slate-500">
                Users can view and use this component.
              </span>
            </span>
          </label>
        </div>

        <div className="pt-5">
          <div className="flex justify-end gap-3">
            <Link
              to="/component/"
              className="rounded-md border border-slate-300 bg-white py-2 px-4 text-sm font-medium text-slate-700 shadow-sm hover:bg-slate-50"
            >
              Cancel
            </Link>
            <button
              type="button"
              onClick={handleSave}
              disabled={saving}
              className="inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 disabled:opacity-60"
            >
              {isUpdate ? "Update" : "Save"}
            </button>
            {isUpdate ? (
              <button
                type="button"
                onClick={handleDelete}
                disabled={deleteState.loading}
                className="inline-flex justify-center rounded-md border border-transparent bg-rose-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-rose-700 disabled:opacity-60"
              >
                Delete
              </button>
            ) : null}
          </div>
        </div>

        {componentQuery.loading || categoriesQuery.loading ? (
          <div className="pt-4 text-sm text-slate-500">Loading...</div>
        ) : null}
      </div>
    </main>
  );
}
