// src/pages/tools/File.tsx
import AppTable from "@/components/AppTable";
import { useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useQuery } from "@apollo/client";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import { FILE_FILES } from "@/graphql/queries/tools";
import { useAuthStore } from "@/store/useAuthStore";
import PaginationFooter from "@/components/PaginationFooter";
import SelectAllCheckbox from "@/components/SelectAllCheckbox";
import TableBulkBar from "@/components/TableBulkBar";
import { DEFAULT_PAGE_SIZE, nextPageVariables } from "@/lib/pagination";
import useRowSelection from "@/hooks/useRowSelection";
import { TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

dayjs.extend(relativeTime);

const perPageOptions = [
  { name: "15", value: 15 },
  { name: "30", value: 30 },
  { name: "100", value: 100 },
  { name: "200", value: 200 },
  { name: "500", value: 500 },
  { name: "1000", value: 1000 },
  { name: "3000", value: 3000 }
];

const limitOptions = [
  { name: "256", value: 256 },
  { name: "500", value: 500 },
  { name: "1000", value: 1000 },
  { name: "3000", value: 3000 }
];

const formatBytes = (bytes: number) => {
  if (!bytes && bytes !== 0) return "0 B";
  if (bytes < 1024) return `${bytes.toFixed(2)} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(2)} KB`;
  if (bytes < 1024 * 1024 * 1024) return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
  return `${(bytes / (1024 * 1024 * 1024)).toFixed(2)} GB`;
};

type FileProps = {
  view?: "select";
  onFile?: (url: string) => void;
};

export default function File({ view, onFile }: FileProps) {
  const user = useAuthStore((state) => state.user);
  const userId = user?.id ?? null;
  const navigate = useNavigate();
  const [first, setFirst] = useState(DEFAULT_PAGE_SIZE);
  const [limit, setLimit] = useState(256);
  const [limitOpen, setLimitOpen] = useState(false);

  const variables = useMemo(
    () => ({
      userId: userId ?? 0,
      first,
      after: null,
      limit
    }),
    [userId, first, limit]
  );

  const { data, loading, refetch, fetchMore } = useQuery(FILE_FILES, {
    variables,
    skip: !userId
  });

  const files = data?.fileFiles?.edges ?? [];
  const fileRows = useMemo(() => files.map((edge: any) => edge.node), [files]);
  const pageInfo = data?.fileFiles?.pageInfo;
  const totalAvailable = data?.fileFiles?.total ?? files.length;
  const hasMore = (pageInfo?.hasNextPage ?? false) || files.length < totalAvailable;

  const { selectedIds, allSelected, indeterminate, toggleAll, toggleOne, clearSelection } = useRowSelection({
    rows: fileRows,
    getId: (file: any) => file.id
  });

  const selectFile = (id: number) => {
    if (view === "select") return;
    navigate(`/tool/file/update/${id}`);
  };

  const copyUrl = async (url: string) => {
    try {
      await navigator.clipboard.writeText(url);
    } catch {
      // ignore
    }
  };

  return (
    <div className="space-y-5">
      <div className="sm:flex sm:items-center">
        <div className="sm:flex-auto relative">
          <h1 className="text-xl font-semibold text-gray-900 flex items-center">
            File
            <button
              type="button"
              onClick={() => refetch()}
              className="ml-2 inline-flex h-6 w-6 items-center justify-center rounded-full border border-gray-200 text-gray-500 hover:text-indigo-600"
            >
              ↻
            </button>
          </h1>
          <p className="mt-2 text-sm text-gray-700">
            Manage and Organize Files and Documents for Easy Access and Collaboration
          </p>
        </div>
        <div className="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
          <Link
            to="/tool/file/create/"
            className="inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700"
          >
            Add New
          </Link>
          <Link
            to="/tool/file/bulk/"
            className="ml-4 inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700"
          >
            Add Bulk
          </Link>
        </div>
      </div>

      <div className="mt-8 flex flex-col">
        <div className="-my-2 -mx-4 overflow-x-auto sm:-mx-4 lg:-mx-4">
          <div className="inline-block min-w-full py-2 align-middle sm:px-5 lg:px-5">
            <div className="table-source-wrap">
              <TableBulkBar selectedCount={selectedIds.length} actions={[]} onClear={clearSelection} />
              <AppTable className="data-table min-w-full divide-y divide-gray-300">
                <TableHeader className="bg-gray-50">
                  <TableRow>
                    <TableHead scope="col" className="relative w-6 px-4 sm:w-6 sm:px-4">
                      SL
                    </TableHead>
                    <TableHead scope="col" className="relative w-5 px-5 sm:w-5 sm:px-5">
                      <SelectAllCheckbox
                        checked={allSelected}
                        indeterminate={indeterminate}
                        disabled={files.length === 0}
                        onChange={toggleAll}
                        ariaLabel="Select all files"
                        className="absolute left-3 top-1/2 -mt-2 h-4 w-4 -translate-y-1/2 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500 sm:left-3"
                      />
                    </TableHead>
                    <TableHead scope="col" className="min-w-[6rem] w-full py-3.5 pl-3 sm:pl-0 pr-3 text-left text-sm font-semibold text-gray-900">
                      Title
                    </TableHead>
                    <TableHead scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900 w-20">
                      Size
                    </TableHead>
                    <TableHead scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900 w-20">
                      Update
                    </TableHead>
                    <TableHead scope="col" className="px-4 py-3.5 text-right text-sm font-semibold text-gray-900 sm:pr-6 w-20">
                      Action
                    </TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody className="divide-y divide-gray-200 bg-white">
                  {files.map((edge: any, index: number) => {
                    const file = edge.node;
                    const safeUrl = file.isSecure && file.url?.includes(".mp4")
                      ? file.url.replace("video", "drm").replace(".mp4", ".m3u8")
                      : file.url;
                    return (
                      <TableRow
                        key={file.id}
                        className={`cursor-pointer active:cursor-wait ${selectedIds.includes(file.id) ? "bg-gray-50" : ""}`}
                      >
                        <TableCell className="whitespace-nowrap bg-yellow-100 text-sm text-gray-500 text-center">{index + 1}</TableCell>
                        <TableCell className="relative w-5 px-5 sm:w-5 sm:px-5">
                          {selectedIds.includes(file.id) ? (
                            <div className="absolute inset-y-0 left-0 w-0.5 bg-indigo-600" />
                          ) : null}
                          <SelectAllCheckbox
                            checked={selectedIds.includes(file.id)}
                            onChange={(checked) => toggleOne(file.id, checked)}
                            ariaLabel={`Select file ${file.title ?? file.id}`}
                            className="absolute left-3 top-1/2 -mt-2 h-4 w-4 -translate-y-1/2 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500 sm:left-3"
                          />
                        </TableCell>
                        <TableCell onClick={() => selectFile(file.id)} className="truncate py-2 pl-3 sm:pl-0 pr-3 text-sm max-w-[170px]">
                          <div className="flex items-center">
                            <div>
                              <div className="font-medium text-gray-900">{file.title}</div>
                            </div>
                          </div>
                        </TableCell>
                        <TableCell onClick={() => selectFile(file.id)} className="whitespace-nowrap px-2 py-2 text-sm text-gray-500">
                          <span className="bg-green-100 text-green-800 inline-flex rounded-full px-2 text-xs font-semibold leading-5">
                            {formatBytes(file.size)}
                          </span>
                        </TableCell>
                        <TableCell onClick={() => selectFile(file.id)} className="whitespace-nowrap px-2 py-2 text-sm text-gray-500">
                          <div className="text-gray-900">{file.updatedAt ? dayjs(file.updatedAt).fromNow() : "—"}</div>
                          <div className="text-gray-500 text-xs">
                            {file.updatedAt ? dayjs(file.updatedAt).format("h:mm A MMM D") : "—"}
                          </div>
                        </TableCell>
                        <TableCell className="whitespace-nowrap px-4 py-2 text-sm text-gray-500 text-right sm:pr-4 flex items-center gap-2">
                          {view === "select" ? (
                            <button
                              type="button"
                              onClick={() => onFile?.(safeUrl)}
                              className="relative inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50"
                            >
                              Select
                            </button>
                          ) : (
                            <>
                              <button
                                type="button"
                                onClick={() => copyUrl(safeUrl)}
                                className="relative inline-flex items-center rounded-l-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50"
                              >
                                URL
                              </button>
                              <button
                                type="button"
                                onClick={() => selectFile(file.id)}
                                className="relative inline-flex items-center rounded-r-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50"
                              >
                                Edit
                              </button>
                            </>
                          )}
                        </TableCell>
                      </TableRow>
                    );
                  })}
                </TableBody>
              </AppTable>
              {!loading && files.length === 0 ? (
                <div className="text-center border-t border-gray-200 bg-white px-4 py-4 sm:px-6">
                  <div className="hidden sm:block">
                    <p className="text-sm text-gray-700">No record :-(</p>
                  </div>
                </div>
              ) : null}
              {files.length >= first || pageInfo?.hasNextPage ? (
                <div className="border-t border-gray-200 bg-white px-4 py-3 sm:px-4">
                  <div className="flex flex-wrap items-center justify-end gap-3">
                    <div className="inline-flex rounded-md shadow-sm">
                      <button
                        type="button"
                        className="relative inline-flex items-center rounded-l-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50"
                      >
                        Max limit
                      </button>
                      <div className="relative -ml-px block">
                        <button
                          type="button"
                          onClick={() => setLimitOpen((prev) => !prev)}
                          className="relative inline-flex items-center rounded-r-md border border-gray-300 bg-white px-2 py-2 text-sm font-medium text-gray-500 hover:bg-gray-50"
                        >
                          {limit}
                          <span className="ml-1">▾</span>
                        </button>
                        {limitOpen ? (
                          <div className="absolute left-0 sm:left-auto sm:right-0 bottom-12 z-10 mt-2 -mr-1 w-56 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none">
                            <div className="py-1">
                              {limitOptions.map((item) => (
                                <button
                                  key={item.name}
                                  type="button"
                                  onClick={() => {
                                    setLimit(item.value);
                                    setLimitOpen(false);
                                  }}
                                  className="block w-full px-4 py-2 text-left text-sm text-gray-700 hover:bg-gray-100"
                                >
                                  {item.name}
                                </button>
                              ))}
                            </div>
                          </div>
                        ) : null}
                      </div>
                    </div>
                  </div>
                  <PaginationFooter
                    count={files.length}
                    total={totalAvailable}
                    from={files.length ? 1 : 0}
                    to={files.length}
                    hasNext={hasMore}
                    onLoadMore={() => {
                      fetchMore({
                        variables: nextPageVariables({
                          baseVariables: { userId: userId ?? 0, limit },
                          pageInfo,
                          currentCount: files.length,
                          pageSize: first
                        })
                      });
                    }}
                    label="files"
                    loading={loading}
                    pageSize={first}
                    pageSizeOptions={perPageOptions.filter((item) => item.value <= limit).map((item) => item.value)}
                    onPageSizeChange={setFirst}
                    nextLabel="Next"
                  />
                </div>
              ) : null}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// site-admin/src/views/tool/File.vue
<template>
  <main
   
    class="px-4 pb-[60px] pt-0 md:pt-0 sm:pb-4"
  >
    <div class="sm:flex sm:items-center">
      <div class="sm:flex-auto relative">
        <h1 class="text-xl font-semibold text-gray-900 flex items-center">
          File
          <BoltIcon
            @click="refetch()"
            class="cursor-pointer active:cursor-wait h-4 w-4 ml-2"
            aria-hidden="true"
          />
        </h1>
        <p class="mt-2 text-sm text-gray-700">
          A list of all the files in your account including their name, title,
          email and role.
        </p>
        <div
          class="absolute z-0 duration-1000 -inset-2 transitiona-all opacity-20 rounded-xl blur-lg filter group-hover:opacity-100 group-hover:-inset-1 group-hover:duration-200"
          style="background:linear-gradient(90deg, rgb(68, 255, 154) -0.55%, rgb(68, 176, 255) 22.86%, rgb(162 147 186) 48.36%, rgb(255, 102, 68) 73.33%, rgb(235, 255, 112) 99.34%);">
        </div>
      </div>
      <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
        <router-link
          :to="`/tool/file/create/`"
          type="button"
          class="inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:ring-offset-2 sm:w-auto disabled:opacity-25"
          >Add New</router-link
        >
        <router-link
          :to="`/tool/file/bulk/`"
          type="button"
          class="inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 ml-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:ring-offset-2 sm:w-auto disabled:opacity-25"
          >Add Bulk</router-link
        >
      </div>
    </div>
    <div class="mx-auto mt-4 w-full">
      <div class="space-y-6 lg:col-span-3 lg:col-start-1">
        <!-- Tabs -->
        <div class="lg:block">
          <div class="border-b border-gray-200">
            <nav class="-mb-px flex space-x-4 overflow-x-auto">
              <div
                @click="toggleTab(tab.name)"
                v-for="tab in tabs"
                :key="tab.name"
                :class="[
                  selectedTab == tab.name
                    ? 'border-purple-500 text-purple-600'
                    : 'border-transparent text-gray-700 hover:border-gray-300 hover:text-gray-700',
                  'whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm cursor-pointer active:cursor-wait',
                ]"
              >
                {{ tab.name }}
              </div>
            </nav>
          </div>
        </div>
      </div>
    </div>
    <div class="mt-8 flex flex-col">
      <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
          <div
            class="relative overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg"
          >
            <div
              v-if="selectedFile.length > 0"
              class="absolute top-0 left-12 flex h-12 items-center space-x-3 bg-gray-50 sm:left-16"
            >
              <!-- <button
                type="button"
                class="inline-flex items-center rounded border border-gray-300 bg-white px-2.5 py-1.5 text-xs font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-30"
              >
                Bulk edit
              </button>
              <button
                type="button"
                class="inline-flex items-center rounded border border-gray-300 bg-white px-2.5 py-1.5 text-xs font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-30"
              >
                Delete all
              </button> -->
            </div>
            <table class="min-w-full divide-y divide-gray-300">
              <thead class="bg-gray-50">
                <tr>
                  <th scope="col" class="relative w-6 px-4 sm:w-6 sm:px-4">
                    SL
                  </th>
                  <th scope="col" class="relative w-5 px-5 sm:w-5 sm:px-5">
                    <input
                      type="checkbox"
                      class="absolute left-3 top-1/2 -mt-2 h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500 sm:left-3"
                      :checked="
                        indeterminate ||
                        selectedFile.length === files.edges.length
                      "
                      :indeterminate="indeterminate"
                      @change="
                        selectedFile = $event.target.checked
                          ? files.edges.map((p) => p.node.id)
                          : []
                      "
                    />
                  </th>
                  <th
                    scope="col"
                    class="min-w-[6rem] w-full py-3.5 pl-3 sm:pl-0 pr-3 text-left text-sm font-semibold text-gray-900"
                  >
                    Title
                  </th>
                  <th
                    scope="col"
                    class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900 w-20"
                  >
                    Size
                  </th>
                  <th
                    scope="col"
                    class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900 w-20"
                  >
                    Update
                  </th>
                  <th
                    scope="col"
                    class="px-4 py-3.5 text-right text-sm font-semibold text-gray-900 sm:pr-6 w-20"
                  >
                    Action
                  </th>
                </tr>
              </thead>
              <tbody class="divide-y divide-gray-200 bg-white">
                <tr
                  v-for="file in files.edges"
                  :key="file.node.id"
                  :class="[selectedFile.includes(file.node.id) && 'bg-gray-50']"
                  class="cursor-pointer active:cursor-wait"
                >
                  <td class="relative w-5 px-5 sm:w-5 sm:px-5">
                    <div
                      v-if="selectedFile.includes(file.node.id)"
                      class="absolute inset-y-0 left-0 w-0.5 bg-indigo-600"
                    ></div>
                    <input
                      type="checkbox"
                      class="absolute left-3 top-1/2 -mt-2 h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500 sm:left-3"
                      :value="file.node.id"
                      v-model="selectedFile"
                    />
                  </td>
                  <td
                    @click="selectFile(file.node.id)"
                    class="whitespace-nowrap py-2 pl-3 sm:pl-0 pr-3 text-sm"
                  >
                    <div class="flex items-center">
                      <div class="">
                        <div class="font-medium text-gray-900">
                          {{ file.node.title }}
                        </div>
                      </div>
                    </div>
                  </td>
                  <td
                    @click="selectFile(file.node.id)"
                    class="whitespace-nowrap px-2 py-2 text-sm text-gray-500"
                  >
                    <span
                      class="bg-green-100 text-green-800 inline-flex rounded-full px-2 text-xs font-semibold leading-5"
                      >{{ formatBytes(file.node.size) }}</span
                    >
                  </td>
                  <td
                    @click="selectFile(file.node.id)"
                    class="whitespace-nowrap px-2 py-2 text-sm text-gray-500"
                  >
                    <div class="text-gray-900">
                      {{ dayjs(file.node.updatedAt).fromNow() }}
                    </div>
                    <div class="text-gray-500 text-xs">
                      {{ dayjs(file.node.updatedAt).format("h:mm A  MMM D") }}
                    </div>
                  </td>
                  <td
                    class="whitespace-nowrap px-4 py-2 text-sm text-gray-500 text-right sm:pr-4"
                  >
                    <button
                      @click="copyUrl(file.node.url)"
                      type="button"
                      class="relative inline-flex items-center rounded-l-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:outline-none"
                    >
                      URL&nbsp;<LinkIcon class="w-4 h-4"/>
                    </button>
                    <button v-if="file.node.url.includes('.mp4')"
                      @click="copySecureUrl(file.node.url)"
                      type="button"
                      class="relative inline-flex items-center border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:outline-none"
                    >
                      Secure&nbsp;<LinkIcon class="w-4 h-4"/>
                    </button>
                    <button
                      @click="selectFile(file.node.id)"
                      type="button"
                      class="relative inline-flex items-center rounded-r-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:outline-none"
                    >
                      <CogIcon
                        class="w-5 h-5 text-gray-700"
                      ></CogIcon>
                    </button>
                  </td>
                </tr>
              </tbody>
            </table>
            <nav
              v-if="files.edges.length == 0"
              class="text-center border-t border-gray-200 bg-white px-4 py-4 sm:px-6"
              aria-label="Pagination"
            >
              <div class="hidden sm:block">
                <p class="text-sm text-gray-700">No record :-(</p>
              </div>
              <div class="flex flex-1 justify-between sm:justify-end">
                <div class="inline-flex rounded-md shadow-sm"></div>
              </div>
            </nav>
            <nav
              v-else-if="files.edges.length != 0 && !hasMore"
              class="text-center border-t border-gray-200 bg-white px-4 py-4 sm:px-6"
              aria-label="Pagination"
            >
              <div class="hidden sm:block">
                <p class="text-sm text-gray-700">No more record :-(</p>
              </div>
              <div class="flex flex-1 justify-between sm:justify-end">
                <div class="inline-flex rounded-md shadow-sm"></div>
              </div>
            </nav>
            <nav v-else-if="files.edges.length >= first || hasMore"
              class="flex items-center justify-between border-t border-gray-200 bg-white px-4 py-3 sm:px-4"
              aria-label="Pagination"
            >
              <div class="hidden sm:block">
                <p class="text-sm text-gray-700">
                  Showing
                  {{ " " }}
                  <span class="font-medium">1</span>
                  {{ " " }}
                  to
                  {{ " " }}
                  <span class="font-medium">{{
                    files.edges ? files.edges.length : 0
                  }}</span>
                </p>
              </div>
              <div class="flex flex-1 justify-between sm:justify-end">
                <div class="inline-flex rounded-md shadow-sm">
                  <button
                    @click="loadMore()"
                    type="button"
                    class="relative inline-flex items-center rounded-l-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:outline-none"
                  >
                    Next
                  </button>
                  <Menu as="div" class="relative -ml-px block">
                    <MenuButton
                      class="relative inline-flex items-center rounded-r-md border border-gray-300 bg-white px-2 py-2 text-sm font-medium text-gray-500 hover:bg-gray-50 focus:z-10 focus:outline-none"
                    >
                      <span class="sr-only">Open options</span>{{ first }}
                      <ChevronDownIcon class="h-5 w-5" aria-hidden="true" />
                    </MenuButton>
                    <transition
                      enter-active-class="transition ease-out duration-100"
                      enter-from-class="transform opacity-0 scale-95"
                      enter-to-class="transform opacity-100 scale-100"
                      leave-active-class="transition ease-in duration-75"
                      leave-from-class="transform opacity-100 scale-100"
                      leave-to-class="transform opacity-0 scale-95"
                    >
                      <MenuItems
                        class="absolute left-0 sm:left-auto sm:right-0 bottom-12 z-10 mt-2 -mr-1 w-56 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none"
                      >
                        <div class="py-1">
                          <MenuItem
                            @click="first = item.value"
                            v-for="item in moreItems"
                            :key="item.name"
                            v-slot="{ active }"
                          >
                            <div
                              :class="[
                                active
                                  ? 'bg-gray-100 text-gray-900'
                                  : 'text-gray-700',
                                'block px-4 py-2 text-sm',
                              ]"
                            >
                              {{ item.name }}
                            </div>
                          </MenuItem>
                        </div>
                      </MenuItems>
                    </transition>
                  </Menu>
                </div>
              </div>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </main>
</template>
<script setup>
import { copyText } from "vue3-clipboard";
import { Menu, MenuButton, MenuItem, MenuItems } from "@headlessui/vue";
import { ChevronDownIcon, BoltIcon, LinkIcon } from "@heroicons/vue/24/outline";
import { ClipboardIcon } from "@heroicons/vue/24/outline";
import { useRouter } from "vue-router";
import { computed, ref, watch, defineAsyncComponent } from "vue";
import { FILE_FILES } from "@/gql/file";
import { useQuery, useMutation } from "@vue/apollo-composable";
import { storeToRefs } from "pinia";
import { useSiteStore } from "@/stores/site";
import { useNotificationsStore } from "@/stores/notifications";
import { useFileStore } from "@/stores/file";
import { useMeStore } from "@/stores/me";
import { useSearchStore } from "@/stores/search";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
const { addNotification } = useNotificationsStore();
dayjs.extend(relativeTime);
const { setFileId } = useFileStore();
const { search } = storeToRefs(useSearchStore());
// file parameter
const first = ref(15);
const after = ref(null);
const hasMore = ref(true);
// end parameter
const router = useRouter();
const { me } = storeToRefs(useMeStore());
const { site } = storeToRefs(useSiteStore());
const selectedFile = ref([]);
const checked = ref(false);
const indeterminate = computed(
  () =>
    selectedFile.value.length > 0 && selectedFile.value.length < files.length
);
// query
const { result, fetchMore, loading, error, refetch } = useQuery(FILE_FILES, {
  userId: me.value.id,
  first: first.value,
  after: after.value,
});
const files = computed(() => result.value?.fileFiles ?? { edges: [] });
const loadMore = () => {
  fetchMore({
    variables: {
      first: first.value,
      after: files.value.fileInfo.endCursor,
    },
    updateQuery: (previousResult, { fetchMoreResult }) => {
      const previousEdges = previousResult.fileFiles.edges;
      const newEdges = fetchMoreResult.fileFiles.edges;
      const fileInfo = fetchMoreResult.fileFiles.fileInfo;
      return newEdges.length
        ? {
            fileFiles: {
              __typename: previousResult.fileFiles.__typename,
              total: previousResult.fileFiles.total,
              edges: [...previousEdges, ...newEdges],
              fileInfo,
            },
          }
        : previousResult;
    },
  });
};
// end query
const selectFile = (fileId) => {
  setFileId(fileId);
  router.push(`/tool/file/update/`);
};
const copyUrl = (url) => {
  copyText(url);
    addNotification(
      {
        title: "File info",
        subTitle: "Successfully copied url.",
      },
      "success"
    );
};
const copySecureUrl = (url) => {
  let filePath = url.replace("video", "drm").replace(".mp4", ".m3u8");
    copyText(filePath);
    addNotification(
      {
        title: "File info",
        subTitle: "Successfully copied url.",
      },
      "success"
    );
};
const selectedTab = ref("All");
const tabs = [
  { id: null, name: "All" },
  { id: 0, name: "Active" },
  { id: 1, name: "Inactive" },
];
const toggleTab = (name) => {
  selectedTab.value = name;
};
watch(selectedTab, () => {
  refetch({
    isActive:
      selectedTab.value == "All"
        ? null
        : selectedTab.value === "Active"
        ? true
        : false,
  });
});
watch(search, () => {
  if (search.value) {
    refetch({ search: search.value ? search.value : null });
  } else {
    refetch({ search: null });
  }
});
const moreItems = [
  { name: "15", value: 15 },
  { name: "30", value: 30 },
  { name: "100", value: 100 },
  { name: "200", value: 200 },
];
const formatBytes = (bytes) => {
  if (bytes < 1024) {
    return bytes.toFixed(2) + " B";
  } else if (bytes < 1024 * 1024) {
    return (bytes / 1024).toFixed(2) + " KB";
  } else if (bytes < 1024 * 1024 * 1024) {
    return (bytes / (1024 * 1024)).toFixed(2) + " MB";
  } else {
    return (bytes / (1024 * 1024 * 1024)).toFixed(2) + " GB";
  }
};
</script>
